# Generated by Django 5.0.6 on 2025-02-20 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0002_amc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='amc_name',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='amc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload_excel.amc'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='MutualFundScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=255)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='upload_excel.amc')),
            ],
        ),
    ]
