# Generated by Django 5.0.6 on 2025-02-20 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0003_rename_upload_date_uploadedfile_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_excel.mutualfundscheme'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='amc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_excel.amc'),
        ),
    ]
