# Generated by Django 5.0.6 on 2025-02-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0004_uploadedfile_scheme_alter_uploadedfile_amc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
