# Generated by Django 5.0.6 on 2025-02-21 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0006_mutualfunddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfunddata',
            name='amc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_excel.amc'),
        ),
    ]
