# Generated by Django 5.0.6 on 2025-02-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0007_mutualfunddata_amc'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='debt_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='equity_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='other_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='total_market_value',
            field=models.FloatField(default=0),
        ),
    ]
