# Generated by Django 5.0.6 on 2025-02-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0008_uploadedfile_debt_total_uploadedfile_equity_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfunddata',
            name='industry_rating',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='instrument_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='instrument_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='isin',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='market_value',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='percentage_to_nav',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='yield_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='ytc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
