# Generated by Django 5.0.6 on 2025-02-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0010_remove_mutualfunddata_column1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfunddata',
            name='market_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfunddata',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mutualfunddata',
            name='scheme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_excel.mutualfundscheme'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload_excel.mutualfundscheme'),
        ),
    ]
