# Generated by Django 5.0.6 on 2025-02-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0011_alter_mutualfunddata_market_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfunddata',
            name='isin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
