# Generated by Django 5.0.6 on 2025-02-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0012_alter_mutualfunddata_isin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfunddata',
            name='top_holdings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mutualfunddata',
            name='top_sectors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
