# Generated by Django 5.0.6 on 2025-02-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0013_mutualfunddata_top_holdings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfunddata',
            name='top_holdings',
        ),
        migrations.RemoveField(
            model_name='mutualfunddata',
            name='top_sectors',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='top_holdings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='top_sectors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
