# Generated by Django 5.0.6 on 2025-02-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0014_remove_mutualfunddata_top_holdings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='update_logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
