# Generated by Django 5.0.6 on 2025-02-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0016_mutualfunddata_uploaded_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mutualfunddata',
            old_name='uploaded_file',
            new_name='file',
        ),
    ]
