# Generated by Django 5.0.6 on 2025-02-27 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0017_rename_uploaded_file_mutualfunddata_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutualfunddata',
            name='file',
        ),
        migrations.AlterField(
            model_name='mutualfunddata',
            name='amc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_excel.uploadedfile'),
        ),
    ]
