# Generated by Django 5.0.6 on 2025-02-27 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0018_remove_mutualfunddata_file_alter_mutualfunddata_amc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfunddata',
            name='amc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_excel.amc'),
        ),
    ]
