# Generated by Django 5.0.6 on 2025-02-27 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0019_alter_mutualfunddata_amc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfunddata',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_excel.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='mutualfunddata',
            name='processed_at',
            field=models.DateField(auto_now=True),
        ),
    ]
