# Generated by Django 5.0.6 on 2025-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_excel', '0020_mutualfunddata_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='debt_total',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='equity_total',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='other_total',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='total_market_value',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='category_total',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
